apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-backend-aydrive
  labels:
    app.kubernetes.io/name: load-balancer-backend-aydrive
spec:
  replicas: 2
  selector:
    matchLabels:
        app.kubernetes.io/name: load-balancer-backend-aydrive
  template:
    metadata:
      labels:
          app.kubernetes.io/name: load-balancer-backend-aydrive
    spec:
      containers:
      - image: selvinlp/serviciousuarios:latest
        name: usuarios
        ports:
        - containerPort: 3000
        
      - image: selvinlp/serviciocrearcarpeta:latest
        name: crearcarpeta
        ports:
        - containerPort: 3001

      - image: selvinlp/servicioeliminarcarpeta:latest
        name: eliminarcarpeta
        ports:
        - containerPort: 3002
      
      - image: selvinlp/servicioeditarcarpeta:latest
        name: editarcarpeta
        ports:
        - containerPort: 3003
      
      - image: selvinlp/serviciopapelera:latest
        name: papelera
        ports:
        - containerPort: 3004
      
      - image: selvinlp/servicioarchivos:latest
        name: archivos
        ports:
        - containerPort: 3005

      - image: selvinlp/serviciomiddleware:latest
        name: middleware
        ports:
        - containerPort: 3010