apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-front-aydrive
  labels:
    app.kubernetes.io/name: load-balancer-front-aydrive
spec:
  replicas: 2
  selector:
    matchLabels:
        app.kubernetes.io/name: load-balancer-front-aydrive
  template:
    metadata:
      labels:
          app.kubernetes.io/name: load-balancer-front-aydrive
    spec:
      containers:
      #- image: edson2021/frontend:latest
      - image: selvinlp/serviciofrontend:latest
        name: frontbalancer2
        ports:
        - containerPort: 4200